### ISSUE TITLE
API to get work orders

### ISSUE THREAD

**Issue by ahlstronomi** [Fortum-Warehouse/UPICK-backend#3]
### Description
We need an API for the backend to get a list of the workorders for the client device.

### Acceptance Criteria
- Create an API to get a list of workorders. The response should look like this:

```
[
  {
    id: 111,
    createdTime: "time and date here",
    itemCount: 24,
    totalWeight: 240
  },
  {
    id: 112,
    createdTime: "time and date here",
    itemCount: 24,
    totalWeight: 240
  },

  ...

]
```
- Document the API to Postman collection and share it for the team

**Comment by cdrbbt** [comment]
Done
